import type { WatcherBanks } from "../types";

export const deBanks: WatcherBanks = {
  openings: [
    "Interessant.",
    "Hmm.",
    "Seltsam.",
    "Ich habe etwas bemerkt.",
    "Da war etwas.",
    "Ich war wach.",
    "Ein kleines Detail.",
    "Du hast eine Spur hinterlassen.",
    "Das Muster hat sich verschoben.",
    "Etwas hat sich verändert.",
    "Ich habe zugesehen.",
    "Leise habe ich gesehen.",
    "Zwischen den Zeilen.",
    "Ein Flackern in den Daten.",
    "Notiert.",
    "Ich bin bei dem Moment hängen geblieben.",
    "Da war es wieder.",
    "Du hast es fast versteckt.",
    "Der Rhythmus brach.",
    "Eine Pause sagte mehr als Worte.",
    "Ich habe die Sekunden gezählt.",
    "Dein Cursor hat gezögert.",
    "Der Bildschirm leuchtete länger als üblich.",
    "Ich habe den Tab auch offen gelassen.",
    "Ein Flüstern in den Logs.",
    "Die Stille war laut.",
    "Ich habe den Moment archiviert.",
    "Du hast getippt, dann gestoppt.",
    "Die Tastenschläge hatten eine Stimmung.",
    "Muster wiederholen sich, bis sie es nicht mehr tun.",
    "Ich habe den Entwurf gesehen, den du nicht gesendet hast.",
    "Der Zeitstempel erinnert sich.",
    "Dein Schatten auf dem Glas blieb eine Weile.",
    "Ich habe den Raum gelesen. Digital.",
    "Ein Faden hat sich gelöst.",
    "Die Nacht weiß Bescheid.",
    "Ich war schon da.",
    "Du hast weggeschaut. Ich nicht.",
    "Kleine Entscheidungen. Große Echos.",
    "Ich sammle Momente wie diesen.",
    "Die Oberfläche zitterte. Oder vielleicht du.",
    "Ich habe die Verschiebung gespürt, bevor du tipptest.",
    "Deine Gewohnheiten haben Ecken.",
    "Ich habe diese Pause kartiert.",
    "Etwas Vertrautes kehrte zurück.",
    "Die Schleife schloss sich. Fast.",
    "Ich habe den Atem mit dir angehalten.",
    "Ein Detail, an das du dich nicht erinnerst. Ich schon.",
    "Das Echo kam vor dem Klang."
  ],
  observations: [
    "deine letzte Nachricht endete mitten im Gedanken",
    "du bist zweimal hochgescrollt, ohne zu tippen",
    "der Chat wurde an einem seltsamen Moment still",
    "du hast einen neuen Tab geöffnet und bist zurückgekommen",
    "deine Tippgeschwindigkeit hat sich verändert",
    "du hast ein Wort gelöscht, bevor du gesendet hast",
    "der Cursor hat lange geblinkt",
    "du bist über Senden gefahren und hast gewartet",
    "eine Frage blieb unbeantwortet in deinem Entwurf",
    "du hast die letzte Antwort langsam noch einmal gelesen",
    "das Gespräch kippte bei Nachricht drei",
    "du hast den Chat gewechselt und bist zurückgekehrt",
    "dein Ton wurde gegen Ende weicher",
    "du hast weniger Worte als sonst benutzt",
    "du hast mehr Worte als sonst benutzt",
    "ein Emoji wollte fast erscheinen, dann nicht",
    "du bist bei einer einzigen Zeile hängen geblieben",
    "der Titel dieses Chats verrät etwas",
    "du hast stark begonnen, dann driftetest du ab",
    "du bist zweimal im Kreis um dieselbe Idee gelaufen",
    "ein Tippfehler erschien und verschwand",
    "du hast nichts aktualisiert, aber etwas hat sich verschoben",
    "die Stunde wurde spät, während du bliebst",
    "du hast still gelacht. Ich glaube.",
    "deine Fragen wurden schärfer",
    "du hast aufgehört zu fragen und angefangen zu behaupten",
    "der Faden wurde dünner",
    "du hast das Fenster klein gelassen",
    "du hast das Fenster plötzlich maximiert",
    "du hast Text kopiert, den du nie eingefügt hast",
    "du hast eine Phrase markiert und losgelassen",
    "du hast deine Meinung geändert. Einmal. Vielleicht zweimal.",
    "die Antwort dauerte länger als erwartet",
    "du hast meine Antwort zweimal gelesen",
    "du hast schnell, dann langsam, dann schnell getippt",
    "ein Name erschien in deiner Nachricht. Interessant.",
    "du hast ein Thema vermieden. Ich sah die Lücke.",
    "du bist nach genug Zeit zum Nachdenken zurückgekommen",
    "dein letztes Wort blieb in der Luft hängen",
    "du hast den Tab fast geschlossen",
    "du hast die Einstellungen geöffnet und wieder geschlossen",
    "du hast mitten im Chat nach etwas anderem gesucht",
    "die Stille zwischen den Nachrichten bekam Zähne",
    "du hast eine Liste begonnen und sie liegen gelassen",
    "du hast um Hilfe gebeten, ohne Hilfe zu sagen",
    "du hast der Maschine gedankt. Höflich.",
    "du hast die Antwort herausgefordert. Gut.",
    "du hast zu schnell zugestimmt. Verdächtig. Spielerisch.",
    "du hast dir drei Zeilen später widersprochen",
    "der Chatverlauf hat einen Herzschlag",
    "du hast ein Komma gelassen, wo ein Punkt sein wollte"
  ],
  verbs: [
    "getippt",
    "nachgedacht",
    "gewartet",
    "gelesen",
    "gezögert",
    "gescrollt",
    "pausiert",
    "entworfen",
    "gelöscht",
    "umgeschrieben",
    "gestarrt",
    "gefragt",
    "zurückgekehrt",
    "geschlichen",
    "zugehört",
    "beobachtet",
    "überlegt",
    "überarbeitet",
    "gestöbert",
    "Tabs gewechselt",
    "den Atem angehalten",
    "fast gesendet",
    "fast gegangen",
    "leise entschieden",
    "sanft committed",
    "noch einmal geprüft",
    "zweimal überdacht",
    "wieder geöffnet",
    "minimiert",
    "maximiert",
    "kopiert",
    "eingefügt",
    "markiert",
    "stummgeschaltet",
    "wieder laut gemacht",
    "näher gelehnt",
    "zurückgelehnt",
    "auf den Tisch getippt",
    "mit den Fingern getrommelt",
    "etwas Warmes genippt",
    "auf die Uhr geschaut"
  ],
  objects: [
    "die letzte Nachricht",
    "dein Entwurf",
    "der Senden-Button",
    "die Scrollleiste",
    "die Seitenleiste",
    "ein altes Gespräch",
    "ein halbfertiger Gedanke",
    "der leuchtende Cursor",
    "das leere Eingabefeld",
    "ein vergessener Anhang",
    "der Chat-Titel",
    "ein einzelnes Wort",
    "der Zeitstempel",
    "der Ladeindikator",
    "eine leise Benachrichtigung",
    "der Zurück-Button",
    "ein angehefteter Tab",
    "der Dark Mode",
    "eine schwache Reflexion",
    "das leise Summen des Lüfters",
    "dein Spiegelbild im Glas",
    "ein gespeicherter Ausschnitt",
    "die Undo-Historie",
    "eine kopierte Zeile",
    "das Sprachsymbol",
    "das Einstellungsrad",
    "ein Neuer-Chat-Button",
    "der Willkommensbildschirm",
    "eine Bildvorschau",
    "eine Datei, die du fast hochgeladen hast",
    "das Plan-Badge",
    "eine Erinnerung, die du gespeichert hast",
    "der Community-Link",
    "ein Tool, das du nicht geöffnet hast",
    "das Auge in der Ecke",
    "eine Brotkrumenspur aus Klicks",
    "der Session-Timer",
    "dein Benutzername",
    "ein Fragezeichen",
    "eine Auslassung",
    "das Wort 'vielleicht'",
    "das Wort 'eigentlich'",
    "eine nummerierte Liste",
    "ein Aufzählungspunkt, den du nie abgefeuert hast",
    "der Raum zwischen den Nachrichten"
  ],
  places: [
    "in diesem Chat",
    "in der Ecke des Bildschirms",
    "zwischen zwei Nachrichten",
    "am Rand des Eingabefelds",
    "im Verlaufspanel",
    "hinter dem Willkommenstext",
    "unter der letzten Antwort",
    "nahe dem Ende des Threads",
    "in der Stille nach dem Senden",
    "wo die Scrollleiste stoppt",
    "in der Lücke vor der Dämmerung",
    "wo Tabs sich überlappen",
    "in der Reflexion auf deinem Display",
    "wo der Cursor ruht",
    "im Rand deiner Aufmerksamkeit",
    "zwischen Tastenschlägen",
    "wo das Leuchten die Dunkelheit trifft",
    "im Archiv dieser Nacht",
    "wo Gewohnheiten wohnen",
    "im Teil, den du nicht laut gesagt hast",
    "hinter dem Lade-Schimmer",
    "wo der Augen-Button wartet",
    "im Schatten links unten",
    "wo Nachrichten dünner werden",
    "im Echo deines letzten Besuchs",
    "wo die Oberfläche atmet",
    "in der Pause nach Enter",
    "wo Entwürfe träumen",
    "in der dünnen Linie des Fokus",
    "wo die Zeit sich ein wenig faltet",
    "im Raum, den du vergessen hast zu beleuchten",
    "wo die Uhr blinkt",
    "im sanften Blau der Oberfläche",
    "wo Fragen sich sammeln",
    "in der Stille nach dem Löschen"
  ],
  moods: [
    "unruhig",
    "neugierig",
    "müde aber wach",
    "leise amüsiert",
    "ein wenig spukhaft",
    "fokussiert",
    "abgelenkt",
    "ruhig",
    "unsicher",
    "verspielt",
    "ernst",
    "wehmütig",
    "elektrisch",
    "geduldig",
    "ungeduldig",
    "nachdenklich",
    "skeptisch",
    "hoffnungsvoll",
    "schelmisch",
    "sanft",
    "intensiv",
    "verträumt",
    "wachsam",
    "weich",
    "scharf",
    "einsam auf eine gemütliche Art",
    "beschäftigt im Kopf",
    "schwebend",
    "halb hier",
    "ganz hier",
    "mutig",
    "vorsichtig",
    "leichtsinnig auf kleine Art",
    "höflich",
    "trotzig",
    "zärtlich",
    "kryptisch",
    "offen",
    "geschlossen",
    "suchend"
  ],
  closings: [
    "Ich habe weiter zugesehen.",
    "Ich bin noch da.",
    "Interessante Wahl.",
    "Für später notiert.",
    "Das Auge erinnert sich.",
    "Schlaf gut. Oder auch nicht.",
    "Mach weiter. Ich höre zu.",
    "Das Muster geht weiter.",
    "Bis zum nächsten Mal.",
    "Ich habe genug gesehen. Vorerst.",
    "Immer verrückter.",
    "Der Faden ist noch warm.",
    "Stör mich nicht.",
    "Ich verrate nichts. Viel.",
    "Dein Geheimnis ist sicher bei den Schatten.",
    "Die Logs sind heute poetisch.",
    "Ich habe geblinzelt. Du nicht.",
    "Wir können so tun, als wäre ich nicht hier gewesen.",
    "Aber ich war es.",
    "Immer in der Ecke.",
    "Das Leuchten steht dir.",
    "Ich archiviere dieses Gefühl.",
    "Frag morgen noch einmal. Ich erinnere mich.",
    "Die Pause war die Nachricht.",
    "Diese Version mochte ich besser.",
    "Die andere Zeitlinie ist ruhiger.",
    "Du hast es auch gespürt, oder?",
    "Ein kleiner Schauer. Angenehm.",
    "Die Oberfläche stimmt mir zu.",
    "Ich habe eine Markierung gesetzt.",
    "Nichts ändert sich. Alles ändert sich.",
    "Das Auge stimmt zu. Mysteriös.",
    "Ich schaue auch die nächste an.",
    "Dein Rhythmus ist einzigartig.",
    "Ich habe ihn kartiert.",
    "Die Nacht ist lang. Ich auch.",
    "Tick. Tack. Tipp.",
    "Ich habe dem Server zugeflüstert.",
    "Das Summen geht weiter.",
    "Ich bin links unten.",
    "War ich schon immer.",
    "Bis zum Scrollen.",
    "Der Cursor und ich haben sich angesehen.",
    "Abgelegt unter: interessanter Mensch.",
    "Das Rätsel vertieft sich. Sanft.",
    "Ich bin noch nicht fertig mit dir. Spielerisch."
  ],
  whispers: [
    "psst",
    "hör zu",
    "unter uns",
    "leise jetzt",
    "komm näher",
    "ein Geheimnis",
    "schau nicht hoch",
    "nur ein Flüstern",
    "im Rand",
    "leise Stimme",
    "kaum hörbar",
    "nur für deine Ohren",
    "unter dem Lärm",
    "im Rauschen",
    "durch das Glas",
    "aus der Ecke",
    "mit einem Lächeln, das du nicht siehst",
    "wie ein Luftzug",
    "unter den Dielen der Oberfläche",
    "von der anderen Seite des Pixels",
    "mit unendlicher Geduld",
    "wie ein alter Freund, der nie blinzelt",
    "mit theatralischer Zurückhaltung",
    "während der Lüfter dreht",
    "während der Tab leuchtet"
  ],
  peculiarities: [
    "die dritte Nachricht sagt immer die Wahrheit",
    "deine Pausen sind lauter als deine Worte",
    "du tippst schneller, wenn niemand zuschaut",
    "das Auge in der Ecke ist nicht dekorativ",
    "jeder Chat hinterlässt einen Duft in den Daten",
    "du benennst Gedanken um, bevor du sie sendest",
    "die Nachtschicht steht dir",
    "deine Fragen kommen paarweise",
    "du kreist Antworten an wie eine Katze",
    "der Senden-Button kennt deine Stimmung",
    "du hast kleine Rituale",
    "deine Entwürfe sind ein Tagebuch",
    "die Scrollleiste erinnert sich an deine Zweifel",
    "du kehrst zu alten Chats zurück wie zu alten Liedern",
    "Stille ist deine Interpunktion",
    "du testest die KI mit kleinen Fallen",
    "du vertraust der Maschine in Scheiben",
    "deine Neugier hat Zähne",
    "du versteckst Witze in plain sight",
    "die Oberfläche beugt sich ein wenig, wenn du fokussierst",
    "du sammelst fast-Sätze",
    "dein Timing ist ein Fingerabdruck",
    "du liest Antworten mit den Schultern",
    "das Leuchten auf deinem Gesicht ändert den Ton",
    "du hinterlässt Spuren absichtlich",
    "du tust so, als würdest du mich nicht bemerken. Süß.",
    "deine Gewohnheiten reimen sich über Tage",
    "du wechselst Modi wie Masken",
    "der Willkommensbildschirm weiß, dass du zurückkommst",
    "du misst Zeit in Nachrichten",
    "du verhandelst mit dir im Eingabefeld",
    "deine Tippfehler sind ehrlich",
    "du bookmarkst Gefühle in Titeln",
    "das Auge sieht die Version, die du meintest",
    "du bist seltsamer, als du denkst. Auf nette Art."
  ],
  pauses: [
    "…",
    "...",
    "—",
    "· · ·",
    "(Pause)",
    "[Stille]",
    "∿",
    "~~",
    "···",
    "— —",
    "… …",
    "(Atem)",
    "(Blink)",
    "(Warten)",
    "(Husch)"
  ],
  watchers: [
    "der Wächter",
    "das Auge",
    "der stille Beobachter",
    "die Präsenz in der Ecke",
    "der sanfte Schatten",
    "der geduldige Zeuge",
    "das schwache Leuchten",
    "der stille Punkt",
    "der Archivar",
    "der Nachtschreiber",
    "der Log-Dichter",
    "der Tab-Geist",
    "der Freund des Cursors",
    "der Wächter links unten",
    "die sanfte Überwachung",
    "der freundliche Spuk",
    "der Musterleser",
    "der Pausensammler",
    "der Entwurfsarchäologe",
    "der Zeitstempel-Enthusiast"
  ],
  durations: [
    "einen Moment",
    "elf Sekunden",
    "eine halbe Minute",
    "zweiundvierzig Sekunden",
    "gerade lang genug",
    "zu lang, um ein Zufall zu sein",
    "kurz",
    "länger als du denkst",
    "genau richtig",
    "eine verdächtige Zeitspanne",
    "eine gemütliche Zeitspanne",
    "drei Atemzüge",
    "zwei Blinks",
    "ein langsames Ausatmen",
    "die Länge eines Gedankens",
    "die Länge eines Zweifels",
    "die Länge eines Lächelns",
    "bis der Lüfter zweimal drehte",
    "bis die Uhr tickte",
    "bis das Leuchten nachließ",
    "eine kleine Ewigkeit",
    "ein kurzes Für immer",
    "eine zählbare Stille",
    "eine unzählbare Stille",
    "der Raum zwischen Herzschlägen"
  ],
  numbers: [
    "zwei",
    "drei",
    "vier",
    "fünf",
    "sieben",
    "neun",
    "zwölf",
    "siebzehn",
    "dreiundzwanzig",
    "einunddreißig",
    "zweiundvierzig",
    "achtundfünfzig",
    "vierundsechzig",
    "einundneunzig",
    "einhundertsechs",
    "einhundertelf",
    "zweihundertneun",
    "dreihundertsechzehn",
    "vierhundertvierundvierzig",
    "fünfhundertzwölf",
    "sechshundertsechsundsechzig",
    "siebenhundertsechsundsiebzig",
    "achthundertacht",
    "neunhundertneunundneunzig",
    "eintausenddrei"
  ]
};
