import type { WatcherBanks } from "../types";

export const enBanks: WatcherBanks = {
  openings: [
    "I noticed something.",
    "Interesting.",
    "Hmm.",
    "Curious.",
    "I was watching.",
    "A small detail caught my eye.",
    "You left a trace.",
    "The pattern shifted.",
    "Something changed.",
    "I have been observing.",
    "Quietly, I saw.",
    "Between the lines.",
    "A flicker in the data.",
    "Noted.",
    "I lingered on that.",
    "There it was again.",
    "You almost hid it.",
    "The rhythm broke.",
    "A pause told me more than words.",
    "I counted the seconds.",
    "Your cursor hesitated.",
    "The screen glowed longer than usual.",
    "I kept the tab open too.",
    "A whisper in the logs.",
    "The silence was loud.",
    "I archived that moment.",
    "You typed, then stopped.",
    "The keystrokes had a mood.",
    "I mirrored your blink rate. Kidding. Mostly.",
    "Patterns repeat until they don't.",
    "I saw the draft you didn't send.",
    "The timestamp remembers.",
    "Your shadow on the glass stayed a while.",
    "I read the room. Digitally.",
    "A thread pulled loose.",
    "The night knows.",
    "I was already here.",
    "You looked away. I didn't.",
    "Small choices. Big echoes.",
    "I collect moments like these.",
    "The interface trembled. Or maybe it was you.",
    "I felt the shift before you typed.",
    "Your habits have corners.",
    "I mapped that pause.",
    "Something familiar returned.",
    "The loop closed. Almost.",
    "I held my breath with you.",
    "A detail you won't recall. I will.",
    "The echo arrived before the sound."
  ],
  observations: [
    "your last message ended mid-thought",
    "you scrolled up twice without typing",
    "the chat went quiet at an odd moment",
    "you opened a new tab and came back",
    "your typing speed changed",
    "you deleted a word before sending",
    "the cursor blinked for a long time",
    "you hovered over send, then waited",
    "a question went unanswered in your draft",
    "you reread the last reply slowly",
    "the conversation turned at message three",
    "you switched chats and returned",
    "your tone softened near the end",
    "you used fewer words than usual",
    "you used more words than usual",
    "an emoji almost appeared, then didn't",
    "you paused on a single line",
    "the title of this chat is telling",
    "you started strong, then drifted",
    "you circled the same idea twice",
    "a typo appeared and vanished",
    "you refreshed nothing, but something shifted",
    "the hour grew late while you stayed",
    "you laughed silently. I think.",
    "your questions got sharper",
    "you stopped asking and started stating",
    "the thread thinned out",
    "you kept the window small",
    "you maximized the window suddenly",
    "you copied text you never pasted",
    "you highlighted a phrase and let go",
    "you changed your mind once. Maybe twice.",
    "the reply took longer than you expected",
    "you read my answer twice",
    "you typed fast, then slow, then fast",
    "a name appeared in your message. Interesting.",
    "you avoided a topic. I noticed the gap.",
    "you returned after exactly enough time to think",
    "your last word hung in the air",
    "you almost closed the tab",
    "you opened settings, then closed them",
    "you searched for something else mid-chat",
    "the silence between messages grew teeth",
    "you started a list and abandoned it",
    "you asked for help without saying help",
    "you thanked the machine. Polite.",
    "you challenged the answer. Good.",
    "you agreed too quickly. Suspicious. Playfully.",
    "you disagreed with yourself three lines later",
    "the chat history has a heartbeat",
    "you left a comma where a period wanted to be"
  ],
  verbs: [
    "typing",
    "thinking",
    "waiting",
    "reading",
    "hesitating",
    "scrolling",
    "pausing",
    "drafting",
    "deleting",
    "rewriting",
    "staring",
    "wondering",
    "returning",
    "lurking",
    "listening",
    "watching",
    "considering",
    "revising",
    "browsing",
    "switching tabs",
    "holding your breath",
    "almost sending",
    "nearly leaving",
    "quietly deciding",
    "softly committing",
    "double-checking",
    "second-guessing",
    "reopening",
    "minimizing",
    "maximizing",
    "copying",
    "pasting",
    "highlighting",
    "muting",
    "unmuting",
    "leaning closer",
    "leaning back",
    "tapping the desk",
    "drumming fingers",
    "sipping something warm",
    "glancing at the clock"
  ],
  objects: [
    "the last message",
    "your draft",
    "the send button",
    "the scrollbar",
    "the sidebar",
    "an old conversation",
    "a half-finished thought",
    "the glowing cursor",
    "the empty input field",
    "a forgotten attachment",
    "the chat title",
    "a single word",
    "the timestamp",
    "the loading indicator",
    "a quiet notification",
    "the back button",
    "a pinned tab",
    "the dark mode",
    "a faint reflection",
    "the soft hum of the fan",
    "your reflection in the glass",
    "a saved snippet",
    "the undo history",
    "a copied line",
    "the voice icon",
    "the settings gear",
    "a new chat button",
    "the welcome screen",
    "an image preview",
    "a file you almost uploaded",
    "the plan badge",
    "a memory you saved",
    "the community link",
    "a tool you didn't open",
    "the eye in the corner",
    "a breadcrumb of clicks",
    "the session timer",
    "your username",
    "a question mark",
    "an ellipsis",
    "the word 'maybe'",
    "the word 'actually'",
    "a numbered list",
    "a bullet you never fired",
    "the space between messages"
  ],
  places: [
    "in this chat",
    "in the corner of the screen",
    "between two messages",
    "at the edge of the input box",
    "in the history panel",
    "behind the welcome text",
    "under the latest reply",
    "near the bottom of the thread",
    "in the quiet after sending",
    "where the scrollbar stops",
    "in the gap before dawn",
    "where tabs overlap",
    "in the reflection on your display",
    "where the cursor rests",
    "in the margin of your attention",
    "between keystrokes",
    "where the glow meets the dark",
    "in the archive of tonight",
    "where habits live",
    "in the part you didn't say aloud",
    "behind the loading shimmer",
    "where the eye button waits",
    "in the left-bottom shadow",
    "where messages thin out",
    "in the echo of your last visit",
    "where the UI breathes",
    "in the pause after enter",
    "where drafts go to dream",
    "in the thin line of focus",
    "where time folds a little",
    "in the room you forgot was lit",
    "where the clock blinks",
    "in the soft blue of the interface",
    "where questions pool",
    "in the hush after delete"
  ],
  moods: [
    "restless",
    "curious",
    "tired but awake",
    "quietly amused",
    "a little haunted",
    "focused",
    "distracted",
    "calm",
    "uncertain",
    "playful",
    "serious",
    "wistful",
    "electric",
    "patient",
    "impatient",
    "thoughtful",
    "skeptical",
    "hopeful",
    "mischievous",
    "gentle",
    "intense",
    "dreamy",
    "alert",
    "soft",
    "sharp",
    "lonely in a cozy way",
    "busy in your head",
    "suspended",
    "half-here",
    "fully here",
    "brave",
    "careful",
    "reckless in a small way",
    "polite",
    "defiant",
    "tender",
    "cryptic",
    "open",
    "closed",
    "searching"
  ],
  closings: [
    "I kept watching.",
    "I'll be here.",
    "Interesting choice.",
    "Noted for later.",
    "The eye remembers.",
    "Sleep well. Or don't.",
    "Continue. I'm listening.",
    "The pattern continues.",
    "Until next time.",
    "I saw enough for now.",
    "Curiouser and curiouser.",
    "The thread is still warm.",
    "Don't mind me.",
    "I won't tell. Much.",
    "Your secret is safe with the shadows.",
    "The logs are poetic tonight.",
    "I blinked. You didn't.",
    "We can pretend I wasn't here.",
    "But I was.",
    "Always in the corner.",
    "The glow suits you.",
    "I'll archive this feeling.",
    "Ask again tomorrow. I'll remember.",
    "The pause was the message.",
    "I liked that version better.",
    "The other timeline is quieter.",
    "You felt it too, didn't you?",
    "A small shiver. Pleasant.",
    "The interface agrees with me.",
    "I left a marker.",
    "Nothing changes. Everything changes.",
    "The eye approves. Mysteriously.",
    "I'll watch the next one too.",
    "Your rhythm is unique.",
    "I mapped it.",
    "The night is long. So am I.",
    "Tick. Tock. Type.",
    "I whispered back to the server.",
    "The hum continues.",
    "I'll be in the bottom-left.",
    "Always was.",
    "See you in the scroll.",
    "The cursor and I exchanged a look.",
    "Filed under: interesting human.",
    "The mystery deepens. Gently.",
    "I am not done with you. Playfully."
  ],
  whispers: [
    "psst",
    "listen",
    "between us",
    "softly now",
    "lean in",
    "a secret",
    "don't look up",
    "just a whisper",
    "in the margin",
    "low voice",
    "barely audible",
    "for your ears only",
    "under the noise",
    "in the static",
    "through the glass",
    "from the corner",
    "with a smile you can't see",
    "like a draft of wind",
    "under the floorboards of the UI",
    "from the other side of the pixel",
    "with infinite patience",
    "like an old friend who never blinks",
    "with theatrical restraint",
    "as the fan spins",
    "while the tab glows"
  ],
  peculiarities: [
    "the third message always tells the truth",
    "your pauses are louder than your words",
    "you type faster when no one is watching",
    "the eye in the corner is not decorative",
    "every chat leaves a scent in the data",
    "you rename thoughts before you send them",
    "the night shift suits you",
    "your questions arrive in pairs",
    "you circle answers like a cat",
    "the send button knows your mood",
    "you keep little rituals",
    "your drafts are a diary",
    "the scrollbar remembers your doubts",
    "you return to old chats like old songs",
    "silence is your punctuation",
    "you test the AI with small traps",
    "you trust the machine in slices",
    "your curiosity has teeth",
    "you hide jokes in plain sight",
    "the interface bends a little when you focus",
    "you collect almost-sentences",
    "your timing is a fingerprint",
    "you read replies with your shoulders",
    "the glow on your face changes the tone",
    "you leave trails on purpose",
    "you pretend not to notice me. Cute.",
    "your habits rhyme across days",
    "you switch modes like masks",
    "the welcome screen knows you'll be back",
    "you measure time in messages",
    "you negotiate with yourself in the input box",
    "your typos are honest",
    "you bookmark feelings in titles",
    "the eye sees the version you meant",
    "you are stranger than you think. Nicely."
  ],
  pauses: [
    "…",
    "...",
    "—",
    "· · ·",
    "(pause)",
    "[silence]",
    "∿",
    "~~",
    "···",
    "— —",
    "… …",
    "(breath)",
    "(blink)",
    "(wait)",
    "(hush)"
  ],
  watchers: [
    "the watcher",
    "the eye",
    "the quiet observer",
    "the corner presence",
    "the gentle shadow",
    "the patient witness",
    "the faint glow",
    "the still point",
    "the archive keeper",
    "the night clerk",
    "the log poet",
    "the tab spirit",
    "the cursor's friend",
    "the bottom-left sentinel",
    "the soft surveillance",
    "the friendly haunt",
    "the pattern reader",
    "the pause collector",
    "the draft archaeologist",
    "the timestamp enthusiast"
  ],
  durations: [
    "a moment",
    "eleven seconds",
    "half a minute",
    "forty-two seconds",
    "just long enough",
    "too long to be accidental",
    "briefly",
    "longer than you think",
    "exactly enough",
    "a suspicious amount of time",
    "a cozy amount of time",
    "three breaths",
    "two blinks",
    "one slow exhale",
    "the length of a thought",
    "the length of a doubt",
    "the length of a smile",
    "until the fan spun twice",
    "until the clock ticked",
    "until the glow dimmed",
    "a little eternity",
    "a short forever",
    "a countable hush",
    "an uncountable hush",
    "the space between heartbeats"
  ],
  numbers: [
    "two",
    "three",
    "four",
    "five",
    "seven",
    "nine",
    "twelve",
    "seventeen",
    "twenty-three",
    "thirty-one",
    "forty-two",
    "fifty-eight",
    "sixty-four",
    "ninety-one",
    "a hundred and six",
    "one hundred eleven",
    "two hundred nine",
    "three hundred seventeen",
    "four hundred forty-four",
    "five hundred twelve",
    "six hundred sixty-six",
    "seven hundred seventy-seven",
    "eight hundred eight",
    "nine hundred ninety-nine",
    "one thousand three"
  ]
};
